version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: "santa_mongo"
    restart: always
    volumes:
      - 'secret-santa:/data/db'
    #    environment:
    #      MONGO_ROOT_USERNAME: santa
    #      MONGO_ROOT_PASSWORD: secret_santa
    ports:
      - 27020:27017
volumes:
  secret-santa:
    driver: local