version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: "santa_mongo"
    restart: always
    #    environment:
    #      MONGO_ROOT_USERNAME: santa
    #      MONGO_ROOT_PASSWORD: secret_santa
    ports:
      - 27020:27017