version: '0.1'

services:

  mongo:
    image: mongo
    container_name: "santa_mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: santa
      MONGO_INITDB_ROOT_PASSWORD: secret_santa
    ports:
      - 27020:27017