# logging configuration
logging:
  level:
    tver.wa: 'INFO'

# application port
server:
  port: 10901

github:
  url: 'https://api.github.com'
  repo: '/repos/yazabara/secret-santa/commits/master'


# spring configuration
spring:
  main:
    allow-bean-definition-overriding: true